### ISSUE TITLE
WaterDrop 2.7 config alignments

### ISSUE THREAD

**Issue by mensfeld** [SberMarket-Tech/sbmt-kafka_producer#1]
Hey, I'm in the process of crafting Karafka 2.4 and WaterDrop 2.7. Wanted bring to your attention the configuration changes and other alignments that may be required on your side. Here are the docs for the upcoming releases: https://karafka.io/docs/Upgrades-2.4/#waterdrop-27-configuration-alignments

**Comment by bibendi** [comment]
Hi! Thanks for letting us know!

**Comment by mensfeld** [comment]
Np. you've been notified, so closing. Beta releases of the whole ecosystem should happen soon. Officials in 2-4 weeks.
